# Reusable GitLab CI template for Postman to k6 Load Testing
# Include this in your project's .gitlab-ci.yml:
# include:
#   - remote: 'https://raw.githubusercontent.com/your-org/postman-to-k6-action/main/gitlab-ci-template.yml'

.postman-to-k6:
  stage: test
  image: node:${NODE_VERSION:-18}
  variables:
    POSTMAN_COLLECTION: "${POSTMAN_COLLECTION:-postman/collection.json}"
    LOAD_PROFILE: "${LOAD_PROFILE:-smoke}"
    NODE_VERSION: "${NODE_VERSION:-18}"
    PROFILES_CONFIG: "${PROFILES_CONFIG:-profiles/load-profiles.yaml}"
    K6_OPTIONS: "${K6_OPTIONS:-}"
    ENVIRONMENT_FILE: "${ENVIRONMENT_FILE:-}"
    ENABLE_AI_PROFILE_GENERATION: "${ENABLE_AI_PROFILE_GENERATION:-false}"
    ENABLE_AI_RESULT_ANALYSIS: "${ENABLE_AI_RESULT_ANALYSIS:-false}"
    AI_API_KEY: "${AI_API_KEY:-}"
    AI_PROVIDER: "${AI_PROVIDER:-openai}"
    AI_MODEL: "${AI_MODEL:-}"
    AI_BASE_URL: "${AI_BASE_URL:-}"
    AI_TIMEOUT: "${AI_TIMEOUT:-30000}"
    AI_MAX_RETRIES: "${AI_MAX_RETRIES:-2}"
  before_script:
    # Install postman-to-k6 converter
    - npm install -g @apideck/postman-to-k6
    # Install system dependencies and tools
    - apt-get update -qq && apt-get install -y -qq curl jq > /dev/null
    # Install yq for YAML parsing
    - |
      YQ_VERSION=$(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | grep tag_name | cut -d '"' -f 4)
      curl -sSfL "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -o /usr/local/bin/yq
      chmod +x /usr/local/bin/yq
    # Install k6
    - |
      K6_VERSION="v0.47.0"
      curl -sSfL "https://github.com/grafana/k6/releases/download/${K6_VERSION}/k6-${K6_VERSION}-linux-amd64.tar.gz" -o /tmp/k6.tar.gz
      tar -xzf /tmp/k6.tar.gz -C /tmp
      cp /tmp/k6-${K6_VERSION}-linux-amd64/k6 /usr/local/bin/k6
      chmod +x /usr/local/bin/k6
      rm -rf /tmp/k6*
    # Install AI dependencies (if AI features enabled)
    - |
      if [ "$ENABLE_AI_PROFILE_GENERATION" == "true" ] || [ "$ENABLE_AI_RESULT_ANALYSIS" == "true" ]; then
        echo "Installing AI dependencies..."
        npm install --prefix /tmp openai
        if [ "$AI_PROVIDER" == "claude" ]; then
          npm install --prefix /tmp @anthropic-ai/sdk || echo "Warning: Could not install Claude SDK"
        fi
        export NODE_PATH=/tmp/node_modules:$NODE_PATH
      fi
  script:
    # Validate Postman collection
    - |
      if [ ! -f "$POSTMAN_COLLECTION" ]; then
        echo "Error: Postman collection file not found at $POSTMAN_COLLECTION"
        exit 1
      fi
      if ! jq empty "$POSTMAN_COLLECTION" 2>/dev/null; then
        echo "Error: Invalid JSON format in Postman collection"
        exit 1
      fi
      echo "Postman collection validated successfully"
    # Analyze collection with AI and generate load profile (if enabled)
    - |
      if [ "$ENABLE_AI_PROFILE_GENERATION" == "true" ]; then
        if [ -z "$AI_API_KEY" ]; then
          echo "Warning: AI profile generation enabled but AI_API_KEY not provided. Skipping AI analysis."
        else
          OUTPUT_DIR=".k6-config"
          OUTPUT_FILE="$OUTPUT_DIR/ai-suggested-profile.yaml"
          mkdir -p "$OUTPUT_DIR"
          
          AI_CONFIG="{"
          AI_CONFIG="$AI_CONFIG\"provider\":\"$AI_PROVIDER\","
          AI_CONFIG="$AI_CONFIG\"apiKey\":\"$AI_API_KEY\","
          if [ -n "$AI_MODEL" ]; then
            AI_CONFIG="$AI_CONFIG\"model\":\"$AI_MODEL\","
          fi
          if [ -n "$AI_BASE_URL" ]; then
            AI_CONFIG="$AI_CONFIG\"baseUrl\":\"$AI_BASE_URL\","
          fi
          AI_CONFIG="$AI_CONFIG\"timeout\":$AI_TIMEOUT,"
          AI_CONFIG="$AI_CONFIG\"maxRetries\":$AI_MAX_RETRIES"
          AI_CONFIG="$AI_CONFIG}"
          
          SCRIPT_PATH=""
          for path in "scripts/ai-profile-generator.js" "./scripts/ai-profile-generator.js"; do
            if [ -f "$path" ]; then
              SCRIPT_PATH="$path"
              break
            fi
          done
          
          if [ -n "$SCRIPT_PATH" ] && [ -f "$SCRIPT_PATH" ]; then
            export NODE_PATH=/tmp/node_modules:$NODE_PATH || true
            echo "Running AI profile generation..."
            node "$SCRIPT_PATH" "$POSTMAN_COLLECTION" "$AI_CONFIG" "$OUTPUT_FILE" || echo "Warning: AI profile generation failed, continuing with default profile"
          fi
        fi
      fi
    # Convert Postman collection to k6 script
    - |
      OUTPUT_FILE="k6-script-$(date +%s).js"
      ENV_FLAG=""
      if [ -n "$ENVIRONMENT_FILE" ] && [ -f "$ENVIRONMENT_FILE" ]; then
        ENV_FLAG="--environment $ENVIRONMENT_FILE"
      fi
      echo "Converting Postman collection to k6 script..."
      postman-to-k6 "$POSTMAN_COLLECTION" -o "$OUTPUT_FILE" $ENV_FLAG
      if [ ! -f "$OUTPUT_FILE" ]; then
        echo "Error: Failed to generate k6 script"
        exit 1
      fi
      echo "k6 script generated: $OUTPUT_FILE"
      echo "$OUTPUT_FILE" > k6-script-path.txt
    # Prepare load profile configuration
    - |
      PROFILE="$LOAD_PROFILE"
      PROFILES_CONFIG="$PROFILES_CONFIG"
      if [ ! -f "$PROFILES_CONFIG" ]; then
        echo "Warning: Profiles config not found, using default smoke profile"
        echo "--vus 5 --duration 1m" > k6-flags.txt
        exit 0
      fi
      # Check if profile exists
      PROFILE_EXISTS=$(yq eval ".profiles.$PROFILE" "$PROFILES_CONFIG" 2>/dev/null)
      if [ "$PROFILE_EXISTS" == "null" ] || [ -z "$PROFILE_EXISTS" ]; then
        echo "Warning: Profile '$PROFILE' not found in config, falling back to smoke"
        PROFILE="smoke"
      fi
      echo "$PROFILE" > profile-name.txt
      # Generate stages array for k6 as proper JSON
      STAGES_COUNT=$(yq eval ".profiles.$PROFILE.stages | length" "$PROFILES_CONFIG")
      if [ "$STAGES_COUNT" -gt 0 ]; then
        mkdir -p .k6-config
        STAGES_FILE=".k6-config/stages.json"
        THRESHOLDS_FILE=".k6-config/thresholds.json"
        yq eval -o=json ".profiles.$PROFILE.stages" "$PROFILES_CONFIG" > "$STAGES_FILE"
        yq eval -o=json ".profiles.$PROFILE.thresholds" "$PROFILES_CONFIG" > "$THRESHOLDS_FILE"
      fi
    # Merge k6 script with profile configuration
    - |
      SCRIPT_FILE=$(cat k6-script-path.txt)
      STAGES_FILE=".k6-config/stages.json"
      THRESHOLDS_FILE=".k6-config/thresholds.json"
      PROFILE_NAME=$(cat profile-name.txt 2>/dev/null || echo "$LOAD_PROFILE")
      if [ -f "$STAGES_FILE" ] && [ -f "$THRESHOLDS_FILE" ]; then
        STAGES_JSON=$(cat "$STAGES_FILE")
        THRESHOLDS_JSON=$(cat "$THRESHOLDS_FILE")
        if [ -n "$STAGES_JSON" ] && [ "$STAGES_JSON" != "null" ] && [ "$STAGES_JSON" != "" ]; then
          MERGE_SCRIPT=""
          for path in "scripts/merge-k6-options.js" "./scripts/merge-k6-options.js"; do
            if [ -f "$path" ]; then
              MERGE_SCRIPT="$path"
              break
            fi
          done
          if [ -n "$MERGE_SCRIPT" ] && [ -f "$MERGE_SCRIPT" ]; then
            echo "Using merge script: $MERGE_SCRIPT"
            node "$MERGE_SCRIPT" "$SCRIPT_FILE" "$STAGES_JSON" "$THRESHOLDS_JSON" "$PROFILE_NAME"
          else
            echo "Warning: merge-k6-options.js not found, using inline merge logic"
            node -e "
              const fs = require('fs');
              let content = fs.readFileSync('$SCRIPT_FILE', 'utf8');
              const stages = JSON.parse('$STAGES_JSON');
              const thresholds = JSON.parse('$THRESHOLDS_JSON');
              const optionsBlock = \`// Load profile: $PROFILE_NAME
        export const options = {
          stages: \${JSON.stringify(stages, null, 2)},
          thresholds: \${JSON.stringify(thresholds, null, 2)},
        };\`;
              if (/export\\s+(const|let|var)\\s+options\\s*=/.test(content)) {
                content = content.replace(/export\\s+(const|let|var)\\s+options\\s*=\\s*\\{[^}]*\\};?/s, optionsBlock);
              } else {
                const lines = content.split('\\n');
                let lastImport = -1;
                for (let i = 0; i < lines.length; i++) {
                  if (/^(import|const.*require|export.*from)/.test(lines[i])) lastImport = i;
                }
                if (lastImport >= 0) {
                  lines.splice(lastImport + 1, 0, '', optionsBlock);
                  content = lines.join('\\n');
                } else {
                  content = optionsBlock + '\\n\\n' + content;
                }
              }
              fs.writeFileSync('$SCRIPT_FILE', content, 'utf8');
            "
          fi
        fi
      fi
    # Run k6 test
    - |
      SCRIPT_FILE=$(cat k6-script-path.txt)
      ADDITIONAL_OPTIONS="$K6_OPTIONS"
      
      # Add JSON output if AI result analysis is enabled
      if [ "$ENABLE_AI_RESULT_ANALYSIS" == "true" ]; then
        mkdir -p .k6-config
        ADDITIONAL_OPTIONS="$ADDITIONAL_OPTIONS --out json=.k6-config/k6-results.json"
        echo "k6 results will be saved to .k6-config/k6-results.json for AI analysis"
      fi
      
      echo "Running k6 test with profile: $LOAD_PROFILE"
      echo "Script: $SCRIPT_FILE"
      if k6 run $ADDITIONAL_OPTIONS "$SCRIPT_FILE"; then
        echo "status=success" > test-status.txt
      else
        echo "status=failure" > test-status.txt
        exit 1
      fi
    # Analyze test results with AI (if enabled)
    - |
      if [ "$ENABLE_AI_RESULT_ANALYSIS" == "true" ] && [ -f test-status.txt ] && grep -q "status=success" test-status.txt; then
        if [ -z "$AI_API_KEY" ]; then
          echo "Warning: AI result analysis enabled but AI_API_KEY not provided. Skipping AI analysis."
        else
          RESULTS_FILE=".k6-config/k6-results.json"
          OUTPUT_DIR=".k6-config"
          
          if [ -f "$RESULTS_FILE" ]; then
            AI_CONFIG="{"
            AI_CONFIG="$AI_CONFIG\"provider\":\"$AI_PROVIDER\","
            AI_CONFIG="$AI_CONFIG\"apiKey\":\"$AI_API_KEY\","
            if [ -n "$AI_MODEL" ]; then
              AI_CONFIG="$AI_CONFIG\"model\":\"$AI_MODEL\","
            fi
            if [ -n "$AI_BASE_URL" ]; then
              AI_CONFIG="$AI_CONFIG\"baseUrl\":\"$AI_BASE_URL\","
            fi
            AI_CONFIG="$AI_CONFIG\"timeout\":$AI_TIMEOUT,"
            AI_CONFIG="$AI_CONFIG\"maxRetries\":$AI_MAX_RETRIES"
            AI_CONFIG="$AI_CONFIG}"
            
            SCRIPT_PATH=""
            for path in "scripts/ai-result-analyzer.js" "./scripts/ai-result-analyzer.js"; do
              if [ -f "$path" ]; then
                SCRIPT_PATH="$path"
                break
              fi
            done
            
            if [ -n "$SCRIPT_PATH" ] && [ -f "$SCRIPT_PATH" ]; then
              export NODE_PATH=/tmp/node_modules:$NODE_PATH || true
              PROFILE_NAME="$LOAD_PROFILE"
              echo "Running AI result analysis for profile: $PROFILE_NAME"
              node "$SCRIPT_PATH" "$RESULTS_FILE" "$AI_CONFIG" "$PROFILE_NAME" "$OUTPUT_DIR" || echo "Warning: AI result analysis failed"
            fi
          else
            echo "Warning: k6 results file not found: $RESULTS_FILE. AI analysis skipped."
          fi
        fi
      fi
  artifacts:
    name: "k6-results-${LOAD_PROFILE}-${CI_PIPELINE_ID}"
    paths:
      - k6-script*.js
      - .k6-config/
      - k6-script-path.txt
      - test-status.txt
      - profile-name.txt
    expire_in: 30 days
    when: always
  after_script:
    - |
      if [ -f test-status.txt ]; then
        cat test-status.txt
      fi

